[package]
name = "twitch_clip_mirror_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
twitch-api-rs = { version = "0.3.0", git = "https://github.com/oldwomanjosiah/twitch-api.rs" }
reqwest = { version = "0.11", features = ["json"] }
once_cell = "1.13"

anyhow = { default-features = false, features = ["std"], version = "1" }
ed25519-dalek = "1"
futures-util = { default-features = false, version = "0.3" }
hex = "0.4"
hyper = { features = [
    "client",
    "server",
    "http2",
    "runtime",
], version = "0.14" }
log = { default-features = false, version = "0.4" }
metrics-runtime = { default-features = false, features = [
    "metrics-exporter-log",
    "metrics-observer-json",
], version = "0.13" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { default-features = false, features = [
    "macros",
    "process",
    "rt-multi-thread",
], version = "1.0" }
tracing = "0.1"
tracing-subscriber = { default-features = false, features = [
    "fmt",
    "tracing-log",
], version = "0.3" }
twilight-gateway = { version = "0.11", default-features = false, features = [
    "zlib-stock",
    "native",
] }
twilight-http = { version = "0.11", default-features = false, features = [
    "decompression",
    "native",
] }
twilight-model = "0.11"
twilight-standby = "0.11"
console-subscriber = {version = "0.1", optional = true}
toml = "0.5"


[features]
default = []
console = ["dep:console-subscriber"]
